name: Ever
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_storage: ^3.1.5
  firebase_database: ^3.0.7
  image_picker: ^0.6.6+4
  intl: ^0.16.1
  flutter_launcher_icons: "^0.7.3"
  flutter_datetime_picker: ^1.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.otf
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 400
        - asset: fonts/Montserrat-Bold.otf
          weight: 700
